//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbContextEntities1 : DbContext
    {
        public DbContextEntities1()
            : base("name=DbContextEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Basvurular> Basvurulars { get; set; }
        public DbSet<EskiCv> EskiCvs { get; set; }
        public DbSet<EskiIlan> EskiIlans { get; set; }
        public DbSet<IsIlani> IsIlanis { get; set; }
        public DbSet<Isveren> Isverens { get; set; }
        public DbSet<Kullanici> Kullanicis { get; set; }
        public DbSet<KullaniciCv> KullaniciCvs { get; set; }
        public DbSet<Rol_Table> Rol_Table { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
