//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EskiIlan
    {
        public int id { get; set; }
        public string SirketIsmi { get; set; }
        public int eskiid { get; set; }
        public string logo { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string Sektor { get; set; }
        public Nullable<System.DateTime> YayimlamaTarihi { get; set; }
        public string Adres { get; set; }
        public string IlanAdi { get; set; }
        public string aciklama { get; set; }
        public int isverenid { get; set; }
    
        public virtual IsIlani IsIlani { get; set; }
        public virtual Isveren Isveren { get; set; }
    }
}
