//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsIlani
    {
        public IsIlani()
        {
            this.Basvurulars = new HashSet<Basvurular>();
            this.EskiIlans = new HashSet<EskiIlan>();
        }
    
        public int id { get; set; }
        public string SirketIsmi { get; set; }
        public int isverenid { get; set; }
        public string logo { get; set; }
        public string aciklama { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string Sektor { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<System.DateTime> YayimlamaTarihi { get; set; }
        public string Adres { get; set; }
        public string IlanAdi { get; set; }
    
        public virtual ICollection<Basvurular> Basvurulars { get; set; }
        public virtual ICollection<EskiIlan> EskiIlans { get; set; }
        public virtual Isveren Isveren { get; set; }
    }
}
