//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public Kullanici()
        {
            this.Basvurulars = new HashSet<Basvurular>();
            this.EskiCvs = new HashSet<EskiCv>();
            this.KullaniciCvs = new HashSet<KullaniciCv>();
        }
    
        public int KullaniciId { get; set; }
        public string Eposta { get; set; }
        public string Sifre { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Rol { get; set; }
    
        public virtual ICollection<Basvurular> Basvurulars { get; set; }
        public virtual ICollection<EskiCv> EskiCvs { get; set; }
        public virtual Rol_Table Rol_Table { get; set; }
        public virtual ICollection<KullaniciCv> KullaniciCvs { get; set; }
    }
}
