//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciCv
    {
        public KullaniciCv()
        {
            this.Basvurulars = new HashSet<Basvurular>();
            this.EskiCvs = new HashSet<EskiCv>();
        }
    
        public int id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Okul { get; set; }
        public int kullaniciid { get; set; }
        public Nullable<double> AGNO { get; set; }
        public string CalisilanYerler { get; set; }
        public string Onyazi { get; set; }
        public string BeklenenUcret { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string Bolum { get; set; }
        public string YerD { get; set; }
        public string resim { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Durum { get; set; }
    
        public virtual ICollection<Basvurular> Basvurulars { get; set; }
        public virtual ICollection<EskiCv> EskiCvs { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
