//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Table
    {
        public Rol_Table()
        {
            this.Admins = new HashSet<Admin>();
            this.Isverens = new HashSet<Isveren>();
            this.Kullanicis = new HashSet<Kullanici>();
        }
    
        public string Rol { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual ICollection<Isveren> Isverens { get; set; }
        public virtual ICollection<Kullanici> Kullanicis { get; set; }
    }
}
